services:
    it-tools:
        image: 'corentinth/it-tools:latest'
        restart: always
        container_name: it-tools
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.it-tools.rule=Host(`it-tools.rpi.local`)"
          - "traefik.http.services.it-tools.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true
